name: Check
on: [ pull_request, push ]
jobs:
  check:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        jruby_version:
        - 9.1.17.0
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: "temurin"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'jruby-${{ matrix.jruby_version }}'
        bundler-cache: false
    - name: show ruby version
      run: ruby -v
    #
    # This step avoids the following error in the JRuby 9.4 test.
    #
    # Gem::LoadError: You have already activated rake 13.0.6,
    # but your Gemfile requires rake 13.1.0. Prepending
    # `bundle exec` to your command may solve this.
    #
    - name: install rake 10.4.2
      run: gem install rake -v 10.4.2
    - name: install embulk.jar
      run: "curl -L -o embulk.jar https://github.com/embulk/embulk/releases/download/v0.9.25/embulk-0.9.25.jar"
    - name: chmod embulk.jar
      run: chmod a+x embulk.jar
    - name: bundle install
      run: ./embulk.jar bundle install --path vendor/bundle
    - name: rake test
      run: bundle exec env RUBYOPT="-r ./embulk.jar -r embulk -r embulk/java/bootstrap" rake test
